- src/logstats.js
We're not doing it yet; so don't make it a thing in the UI
> Remove runner metrics from logstats

- src/components/repolist/RepoList.js
> Provide an icon to the upgrade link so that people can upgrade their login token to add things to CI.

- src/actions/ui.js
> When the uisvc is down, do not break in react

- src/components/runtable/formatters.js
> Link to tree @ sha for given run

- src/log.js
- src/logstats.js
@capoferro I could really use your input here.
This works. it's functionally complete, works great, etc.
But!
* it now needs two API calls per page load due to architecture ... issues. Please read the patch to see some of these things.
* it's not a very clean patch, i'm passing react components to others for example.
I could use some advice on how to improve this. Thanks!
> Auto-refresh states on log page

- src/components/task-list/index.js
> support task count management in submission -> task lists

- src/lib/table-formatters/index.js
Soon we will want to establish per-level filtering; filtering by task
and run too.
> filter submissions instead of tasks (for now).

- src/lib/table-formatters/index.js
> Fix link in repository widget

- src/components/run-list/index.js
- src/components/submission-list/index.js
- src/components/task-list/index.js
> Control scrolly bits by using CSS

- src/components/main-ui/index.js
> Fix horizontal scrollbars in more places

- src/components/submission-list/index.js
> Propagate cancel status to UI

- src/components/submission-list/index.js
- src/lib/table-formatters/index.js
- yarn.lock
Currently is only managed by github PRs. Will expand to other types once the backends support it.
> Show ticket IDs in submissions

- src/App.js
- src/components/breadcrumb/index.js
- src/components/data-grid/index.js
- src/components/main-ui/index.js
- src/components/submission-list/index.js
- src/components/submission-run-list/index.js
- src/components/task-list/index.js
- src/lib/column-sizer/index.js
- src/lib/table-formatters/index.js
- yarn.lock
Additionally:
- refactor tabled sections:
- to use more detailed formatters
- to share a global wrapper
- Add "runs for submission" pages
- Update client and dependencies
> Rewrite tabular UI to be more spacious

- src/components/submission-run-list/index.js
- src/lib/table-formatters/index.js
- Fix name display in submission runs list
- Condense rows in links table on submission list
> A few more tidbits of polish

- src/lib/table-formatters/index.js
> Fix sha link for submissions list

- src/components/add-to-ci/index.js
- src/components/main-ui/index.js
- src/components/submit-form/index.js
- src/components/subscribed-list/index.js
- src/muitheme.js
> Fix issues with zIndex in menus, other color corrections

- src/components/repo-search/index.js
- src/lib/table-formatters/index.js
Two small changes:
* Open PR links in a new window
* Adjust colors in repo selection lists to be more visible with new theme
> Open ticket ID links in a new window

- src/components/run-list/index.js
- src/components/submission-run-list/index.js
- src/lib/table-formatters/index.js
- 'Ran On' listing shows what hosts ran your run
- Changed log button to have a higher contrast font color and center the
button.
> New features/improvements:

- src/App.js
- src/components/breadcrumb/index.js
* change font to roboto, material-ui recommended font
* adjust home icon in breadcrumb to line up with other elements in the breadcrumb
> Change UI elements to be more consistent

- src/components/data-grid/index.js
> Remove table header from all data tables

- src/components/breadcrumb/index.js
- src/components/log-ui/index.js
- src/components/run-grid/index.js
will touch up the components for history and ref in a later commit.
> Fix some issues with the run grid

- package.json
- src/components/breadcrumb/index.js
- src/components/run-list/index.js
- src/components/submission-list/index.js
- src/components/submission-run-list/index.js
- src/components/task-list/index.js
- src/lib/table-formatters/index.js
- yarn.lock
> re-work history table to be more concise, and display more data.

- src/lib/table-formatters/index.js
> Fix history formatting where there were no times

- src/lib/table-formatters/index.js
> improve the visuals & spacing on several components in the submission information formatter.

- src/components/run-grid/index.js
> Fix issue caught by linter

- src/lib/table-formatters/index.js
> Remove increased font sizes from buttons, tweak icon sizes in submission list

- src/components/breadcrumb/index.js
- src/components/data-grid/index.js
- src/components/run-list/index.js
- src/components/submission-list/index.js
- src/components/submission-run-list/index.js
- src/components/task-list/index.js
> Fix breadcrumb display switching over runs and tasks.

- src/lib/table-formatters/index.js
> Fix moment formatter so that it represents minutes, not months.

- package.json
- yarn.lock
> Upgrade serialize-javascript

- src/components/submit-form/index.js
> Focus repository field on opening of submit form

- src/lib/table-formatters/index.js
> truncate branch name button text on log screen

- Makefile
- package.json
- yarn.lock
* also node 11 in makefile
* also duplicate scripts key in package.json
Signed-off-by: Christopher Maujean <christopher@maujean.org>
> fixing funky yarn/jest dependency

- task.yml
> add package.json testing

- task.yml
> Upgrade node for great justice (but actually, to fix the tests)
